from subprocess import call
from time import sleep

call('echo Fetching all updates...', shell=True)
call('git fetch --all', shell=True)
sleep(1)
call('echo pulling latest changes...', shell=True)
call('git pull', shell=True)
sleep(1)
call('echo Installing backend dependencies...', shell=True)
call('npm install', shell=True)
sleep(1)
call('echo Auditing dependencies...', shell=True)
call('npm audit', shell=True)
sleep(1)
call('echo Not Fixing dependencies in case of errors...', shell=True)
sleep(1)
call('echo Reloading backend through pm2...', shell=True)
call('pm2 reload keysocket --update-env', shell=True)
sleep(1)
call('echo Reloading nginx...', shell=True)
call('sudo systemctl reload nginx', shell=True)
sleep(1)
call('echo Checking nginx status...', shell=True)
sleep(1)
call('sudo systemctl status nginx', shell=True)
sleep(1)
call('echo Checking pm2 status...', shell=True)
sleep(1)
call('pm2 status keysocket', shell=True)
sleep(1)
call('echo Update and reload complete!', shell=True)
sleep(1)