from subprocess import call

def sleep(seconds):
    call(f'sleep {seconds}', shell=True)

call('echo Fetching all updates...', shell=True)
call('git fetch --all', shell=True)
sleep('1s')
call('echo pulling latest changes...', shell=True)
call('git pull', shell=True)
sleep('1s')
call('echo Installing backend dependencies...', shell=True)
call('npm install', shell=True)
sleep('1s')
call('echo Auditing dependencies...', shell=True)
call('npm audit', shell=True)
sleep('1s')
call('echo Fixing dependencies...', shell=True)
call('npm audit fix', shell=True)
sleep('1s')
call('echo Reloading backend through pm2...', shell=True)
call('pm2 reload 0', shell=True)
sleep('1s')
call('echo Reloading nginx...', shell=True)
call('sudo systemctl reload nginx', shell=True)
sleep('1s')
call('echo Checking nginx status...', shell=True)
sleep('1s')
call('sudo systemctl status nginx', shell=True)
sleep('1s')
call('pm2 status 0', shell=True)
call('echo Update and reload complete!', shell=True)
sleep('1s')